plugins {
    id 'com.android.library'
}

android {
    namespace 'com.example.customtoast'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
    lint {
        abortOnError false
    }
        sourceCompatibility JavaVersion.VERSION_1_8
    lint {
        abortOnError false
    }
        targetCompatibility JavaVersion.VERSION_1_8
    lint {
        abortOnError false
    }
    }
    lint {
        abortOnError false
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.facebook.rebound:rebound:0.3.8'
}